version: "3.7"
services:
  mysql-ecomm:
    image: mysql
    container_name: mysql-ecomm
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret

  mongo-ecomm:
    image: mongo
    restart: always
    container_name: mongo-ecomm
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"

  mongo-seed:
    image: mongo
    container_name: mongo-seed
    links:
      - mongo-ecomm
    volumes: 
      - "./mongo-seed:/mongo-seed"
    command: /bin/bash "/mongo-seed/import.sh"
    
  product:
    build: ./product
    container_name: ecomm-product

  account:
    build: ./account
    container_name: ecomm-account