version: "3.7"
services:
  mysql-ecomm:
    image: mysql
    container_name: mysql-ecomm
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db-mysql-ecomm:/var/lib/mysql

  mongo-ecomm:
    image: mongo:5
    restart: always
    container_name: mongo-ecomm
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017

  mongo-seed:
    image: mongo:5
    container_name: mongo-seed
    links:
      - mongo-ecomm
    volumes: 
      - "./mongo-seed:/mongo-seed"
    command: /bin/bash "/mongo-seed/import.sh"
    
  product:
    build: ./product
    container_name: ecomm-product
    ports: 
      - 3002:3002
    environment:
      - DB_HOST=mongo-ecomm
    depends_on:
      - mongo-ecomm
    volumes:
      - ./product:/app-node

  account:
    build: ./account
    container_name: ecomm-account
    ports:
      - 3003:3003
    environment:
      - DB_HOST=mongo-ecomm
    depends_on:
      - mongo-ecomm
    volumes:
      - ./account:/app-node

  finance:
    build: ./finance
    container_name: ecomm-finance
    ports:
      - 3004:3004
    volumes:
    - ./finance:/app-node

  order:
    build: ./order
    container_name: ecomm-order
    ports:
      - 3005:3005
    volumes:
      - ./order:/app-node
volumes:
  db-mysql-ecomm: