version: "3.7"
services:
  mongo-ecomm:
    image: mongo
    restart: always
    container_name: mongo-ecomm
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"

  mongo-seed:
    image: mongo
    container_name: mongo-seed
    links:
      - mongo-ecomm
    volumes: 
      - "./mongo-seed:/mongo-seed"
    command: mongoimport --uri "mongodb://admin:secret@mongo-ecomm:27017/?authSource=admin" --db ecomm-product --collection products --type=csv --file /mongo-seed/ecomm-produtos.csv --headerline

  mongo-seed2:
    image: mongo
    container_name: mongo-seed2
    links:
      - mongo-ecomm
    volumes: 
      - "./mongo-seed:/mongo-seed"
    command: mongoimport --uri "mongodb://admin:secret@mongo-ecomm:27017/?authSource=admin" --db ecomm-product --collection categories --type=csv --file /mongo-seed/ecomm-categorias.csv --headerline

  ecomm-product:
    image: carolinaguisso/ecomm-product:1.0
    container_name: ecomm-product

  account:
    build: ./account
    container_name: ecomm-account